### ISSUE TITLE
Extension Support

### ISSUE THREAD

**Issue by imkrishnaagrawal** [dionmunk/vscode-notes#11]
Right now extension Only Supports the `.md` extension by default. could you add support for other file formats? I have made a quick hack to support the `.adoc` extension in compiled code. adding support for other formats would be great

**Comment by dionmunk** [comment]
I believe this could be set up as a configuration option for the extension. I'll look into this.

**Comment by cklppt** [comment]
Yeah, same wish here.
I was here about to ask where can I find another simple notes extension like this BUT supports file format.

Most my notes are just temp SQLs, json, UUIDs, unfinished code... etc.
Just want a quick note taking extension with sidebar management and file format support.
Surprisingly hard to find one like this. I thought there must be some oldest and popular extensions already solve this.

**Comment by dionmunk** [comment]
Resolved by https://github.com/dionmunk/vscode-notes/commit/a7f1c41b4d47aacb3dcd52656232255cce844130.
