### ISSUE TITLE
Remote SSH doesn't use local location

### ISSUE THREAD

**Issue by Speierers** [dionmunk/vscode-notes#23]
Hi, 

First of all, thanks for the great plugin.

I am constantly working with many VSCode instances opened, all connected to a different machine via `Remote - SSH`. I would like all these instances to share the same notes but unfortunately it looks like the `Notes.notesLocation` isn't correctly resolved on the remote sessions.

Ideally they would all use my local location and ignore the fact that they are remotely connected to another machine. Any idea if this is possible?

Thanks!

**Comment by CMinHong** [comment]
> 
I have the same problem with you, but sooner I find that vscode can use different configuration by user/remote/workspace/folders, so just modify two configurations like this, can solve this problem.
![image](https://user-images.githubusercontent.com/12382933/171401517-45ae8724-766e-4b06-bb0d-694f3c63dee1.png)

**Comment by oliora** [comment]
Can this be reconsidered as a configured feature? I don't need notes on remote servers where I develop code and prefer that all VS code instances share the same local notes location.
