### ISSUE TITLE
Icon missing on Mac

### ISSUE THREAD

**Issue by josephzidell** [dionmunk/vscode-notes#28]
Thanks for this awesome plugin! I use it every day!

Which is why I'm wondering where the icon went? Am on a Mac.

The plugin is enabled, but the icon disappeared 😢 

<img width="517" alt="image" src="https://user-images.githubusercontent.com/1812443/161631291-7fe18c17-6ffe-4afb-88ee-26728014c5f4.png">

**Comment by dionmunk** [comment]
Have you tried right-clicking on the icons and making sure there is a ✅ next to the "Notes" entry?
