### ISSUE TITLE
Support cloud-save function

### ISSUE THREAD

**Issue by chen1415** [dionmunk/vscode-notes#30]
Can we add a function, to save some of the notes to the cloud?
So when user change their PCs, some notes can be synced, as well as the  settings of the VSCode.

Do we have a plan to do this in the future?

**Comment by dionmunk** [comment]
I don't plan on trying to implement a feature that allows Notes to store notes in VSCode's cloud. I built the extension to enable you to select any directory you want to store your notes so you can keep them in Google Drive, Dropbox, One Drive, etc., making them accessible from anywhere and being cross-platform.
