### ISSUE TITLE
command 'Notes.newNote' not found

### ISSUE THREAD

**Issue by securitymonster** [dionmunk/vscode-notes#48]
Just installed version v1.1.0 of Notes on VSC 1.76.2. I selected a storage location, but afterwards none of the Notes commands work:

command 'Notes.newNote' not found
command 'Notes.refreshNotes' not found

Even trying to setup a new location doesn't work:

command 'Notes.setupNotes' not found

I restarted VSC, removed the extension, installed it again. No luck. The icon is there in the activity bar and opens up a Notes window, but it is empty and I can't make new notes there.

**Comment by securitymonster** [comment]
Oops, found the error. My VSC settings.json was missing a comma!

**Comment by ismailhkose** [comment]
This still doesn't work. Why doesn't it have default value?

command 'Notes.refreshNotes' not found
command 'Notes.newNote' not found

I already set "Notes Location" in configurations for my remote settings. It's still doesn't work.
<img width="283" alt="image" src="https://github.com/dionmunk/vscode-notes/assets/353824/e233c035-e3f4-45f1-8b74-2f37da7d41ab">
