### ISSUE TITLE
When I connect to SSH, the content inside is gone. May I ask how to handle it?

### ISSUE THREAD

**Issue by baiduxxoo** [dionmunk/vscode-notes#51]
When I connect to SSH, the content inside is gone. May I ask how to handle it?thank you

**Comment by dionmunk** [comment]
You need to edit your `settings.json` and add the following:
```
"remote.extensionKind": {
    "dionmunk.vscode-notes": ["ui"]
}
```
This will force the Notes extension to run locally and use your local notes folder.
