### ISSUE TITLE
Would it be possible to make keyboard shortcuts (`ALT+N`,  `ALT+L`) configurable in future release

### ISSUE THREAD

**Issue by afknoche** [dionmunk/vscode-notes#55]
Reason is an -- admittedly very specific -- issue with using ALT+L on a Mac with German keyboards. ALT+L is used to type the ‘@' symbol... 

Which means that when the (otherwise very nice extension !) is enabled it is not possible to type  ‘@' in visual code.
 
Obviously it still can be copied and also the extension can be disabled for the time being, so just a nuissance.... But I'm programming with python a bit more now (using decoraters and so), and then it becomes an obvious issue. 

Just a suggestion, like the extension...

**Comment by dionmunk** [comment]
You can change the shortcut keys by opening the Command Pallet (CTRL+Shift+P on Windows or CMD+Shift+P on Mac), type in `Keyboard Shortcuts`, and selecting `Preferences: Open Keyboard Shortcuts`.

Search for `Notes: List Notes` and you will see the shortcut for this set to ALT+L on Windows or OPT+L on Mac. Double-click the entry or click the pencil icon on the left side to edit this shortcut. It will ask you to press the new shortcut keys you want. The key combination should show up in the box when you press them. Then hit Enter/Return to save your new shortcut.

**Comment by afknoche** [comment]
It does the trick nicely. 
(I just changed OPT+L to OPT+SHIFT+L -- but that is just me ;-) )

Thank you very much for your support! Now I can keep the extension enabled when working with python.
