### ISSUE TITLE
use standard size icon for activity bar 

### ISSUE THREAD

**Issue by GorvGoyl** [dionmunk/vscode-notes#6]
please use standardize icon size. icon is too tall in height.

![image](https://user-images.githubusercontent.com/7106086/83669508-503a8280-a5ef-11ea-8696-60a5fa86d18e.png)

P.S: kudos for extension. simple and gets the job done.

**Comment by dionmunk** [comment]
I agree with you and plan on fixing this.

**Comment by xianghongai** [comment]
![preview](https://user-images.githubusercontent.com/2075006/159121127-abc2d6f4-0eb3-4eff-876c-713fd3f6a986.png)

![note](https://user-images.githubusercontent.com/2075006/159121133-44c06e56-369b-4bdc-a536-091a14e3b90d.svg)

**Comment by Sarctiann** [comment]
I'm actually trying to put the button in the sidebar on the right, and looks worse :(
![image](https://github.com/dionmunk/vscode-notes/assets/49457785/6e6d78ce-6ed8-4d6e-9ad4-fd4810579882)

**Comment by dionmunk** [comment]
Resolved by https://github.com/dionmunk/vscode-notes/commit/a8feb970ce00dff80da039571f3522bcedbf0d42.
