### ISSUE TITLE
where is the source code?

### ISSUE THREAD

**Issue by adelphes** [dionmunk/vscode-notes#7]
The repository only contains the build output files. Why is the original source not commited?

**Comment by ToX82** [comment]
I agre with the source code request. Also, I'd be glad to contribute with some PRs if I can

**Comment by dionmunk** [comment]
I'll be updating the repository shortly with the source rather than the compiled code.

**Comment by ironicnet** [comment]
+1
I would like to send some improvements

**Comment by dionmunk** [comment]
Apologies for the delay! Source has been committed.
